apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-operator
spec:  
  interval: 10m
  upgrade:
    timeout: 10m0s
  install:
    timeout: 10m0s
    remediation:
      retries: -1
  chart:
    spec:
      chart: charts/opentelemetry-operator
      sourceRef:
        kind: GitRepository
        name: opentelemetry-operator        
  test:
    enable: true
  values:
    manager: 
      resources:
        limits:
          cpu: 500m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi
      env:
        ENABLE_WEBHOOKS: "false"
    admissionWebhooks:
      create: false