apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: opentelemetry-operator
  namespace: default
spec:
  interval: 5m
  url: 'https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-operator'
